#!/usr/bin/env bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

PACKAGES=(kitty nvim)

for pkg in "${PACKAGES[@]}"; do
	stow -vRt "$HOME" "$pkg"
done

if ! grep -qF "$DIR/bash/.custom_bashrc" "$HOME/.bashrc"; then
        echo "source $DIR/bash/.custom_bashrc" >> "$HOME/.bashrc"
fi
