#!/usr/bin/env bash
set -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

PACKAGES=(kitty nvim niri waybar fuzzel fastfetch)

for pkg in "${PACKAGES[@]}"; do
	stow -vRt "$HOME" "$pkg"
done

sudo stow -vRt / greetd

if ! grep -qF "$DIR/bash/.custom_bashrc" "$HOME/.bashrc"; then
        echo "source $DIR/bash/.custom_bashrc" >> "$HOME/.bashrc"
fi
