[main]
font=AdwaitaMono Nerd Font:size=14
dpi-aware=no
prompt="❯ "
icon-theme=Papirus-Dark
terminal=kitty -e

# Layout
line-height=21
lines=10
width=40
horizontal-pad=20
vertical-pad=20
inner-pad=10

# Borda e Espessura
layer=overlay
exit-on-keyboard-focus-loss=yes

[colors]
background=191724dd
text=e0def4ff
match=ebbcbaff
selection=26233aff
selection-text=e0def4ff
selection-match=f6c177ff
border=f6c177dd

[border]
width=2
radius=10

[dmenu]
mode=text
exit-immediately-if-empty=yes
