[terminal]
vt = 7

[default_session]
command = "tuigreet --time --cmd 'dbus-run-session niri --session' --remember --theme 'time=blue;container=brightblack;prompt=cyan;border=magenta'"
user = "greetd"
